export const FETCH_PROFILE = "FETCH_PROFILE"
export const UPDATE_FIRST_NAME = "UPDATE_FIRST_NAME";
export const UPDATE_LAST_NAME = "UPDATE_LAST_NAME";
export const ADD_HOBBY = "ADD_HOBBY";
export const UPDATE_HOBBIES = "UPDATE_HOBBIES";
export const ADD_SKILL = "ADD_SKILL";
export const UPDATE_SKILLS = "UPDATE_SKILLS"
export const UPDATE_IDENTITY = "UPDATE_IDENTITY"